# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['engine.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('dark_search.py', '.'),
        ('hashcracker.py', '.'),
        ('sql_scanner.py', '.'),
        ('security_levels.py', '.'),
        ('request_repeater.py', '.'),
        ('dom_manipulator.py', '.'),
    ],
    hiddenimports=[
        'PyQt5',
        'PyQt5.QtWebEngineWidgets',
        'PyQt5.QtWebChannel',
        'PyQt5.QtCore',
        'PyQt5.QtGui',
        'PyQt5.QtWidgets',
        'stem',
        'stem.control',
        'stem.Signal',
        'requests',
        'bs4',
        'hashlib',
        'socket',
        're',
        'webbrowser',
        'subprocess',
        'shutil',
        'urllib.parse',
        'concurrent.futures',
        'hashcracker',
        'sql_scanner',
        'security_levels',
        'request_repeater',
        'dom_manipulator',
        'dark_search',
    ],
    hookspath=[],
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='SecureBrowser',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
